// ── Schema Parser ─────────────────────────────────────────────────
// Deprecated — schema.json now contains the pre-built tools array
// generated by extract-schema.js. Nothing imports this file anymore.
// Kept as a placeholder to avoid breaking any stale imports.
