// ── Schema Parser ─────────────────────────────────────────────────
// Imports the rich schema.json generated by extract-schema.js.
// Run: node src/components/chat/extract-schema.js schema.old.ts

import schema from "./schema.json";

export type ColumnDef = {
  type: string;
  nullable: boolean;
  enumValues?: string[];
};

export type TableDef = {
  columns: Record<string, ColumnDef>;
  requiredOnInsert: string[];
  relationships: {
    foreignKey: string;
    columns: string[];
    isOneToOne: boolean;
    referencedTable: string;
    referencedColumns: string[];
  }[];
};

export const RUNTIME_SCHEMA: Record<string, TableDef> = schema as Record<
  string,
  TableDef
>;
