// ── Supabase ──────────────────────────────────────────────────────
// Handles all communication with the Supabase database.
// Uses the authenticated user's session token for all requests
// so RLS treats every call as that specific user.
// Tools are pre-generated by extract-schema.js into tools.json.

import { createClient } from "@supabase/supabase-js";
import prebuiltTools from "./tools.json";

// Base client — used for auth operations only
export const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY,
);

// ── Authenticated client ──────────────────────────────────────────

export async function getAuthenticatedClient() {
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session) return supabase;

  return createClient(
    import.meta.env.VITE_SUPABASE_URL,
    import.meta.env.VITE_SUPABASE_ANON_KEY,
    {
      global: {
        headers: {
          Authorization: `Bearer ${session.access_token}`,
        },
      },
    },
  );
}

// ── Session user ──────────────────────────────────────────────────

export type SessionUser = {
  id: string;
  email: string | undefined;
  metadata: Record<string, any>;
};

export async function getSessionUser(): Promise<SessionUser | null> {
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session?.user) return null;

  const { user } = session;
  console.log("[IA] session user:", user.id, user.email);
  return {
    id: user.id,
    email: user.email,
    metadata: user.user_metadata ?? {},
  };
}

// ── Tool generation ───────────────────────────────────────────────
// Tools are pre-built by extract-schema.js — just return them directly.

export type IATool = {
  name: string;
  description: string;
  input_schema: object;
};

export function buildToolsFromSchema(): IATool[] {
  console.log("[IA] tools loaded:", (prebuiltTools as IATool[]).length);
  return prebuiltTools as IATool[];
}

// ── Tool Execution ────────────────────────────────────────────────

export async function executeTool(
  name: string,
  input: Record<string, unknown>,
): Promise<string> {
  const client = await getAuthenticatedClient();

  if (name === "list_tables") {
    return JSON.stringify({ tables: Object.keys(RUNTIME_SCHEMA) });
  }

  const match = name.match(/^(query|create|update|delete)_(.+)$/);
  if (!match) return JSON.stringify({ error: `Unknown tool: ${name}` });

  const [, cmd, tablename] = match;

  switch (cmd) {
    case "query": {
      let query = client.from(tablename).select("*");
      const filters = input.filters as Record<string, unknown> | undefined;
      if (filters) {
        for (const [key, value] of Object.entries(filters)) {
          query = query.eq(key, value as string);
        }
      }
      const { data, error } = await query;
      if (error) return JSON.stringify({ error: error.message });
      return JSON.stringify({ [tablename]: data });
    }

    case "create": {
      const { data, error } = await client
        .from(tablename)
        .insert(input.data as object)
        .select()
        .single();
      if (error) return JSON.stringify({ error: error.message });
      return JSON.stringify({ [tablename]: data });
    }

    case "update": {
      const { data, error } = await client
        .from(tablename)
        .update(input.data as object)
        .eq("id", input.id as string)
        .select()
        .single();
      if (error) return JSON.stringify({ error: error.message });
      return JSON.stringify({ [tablename]: data });
    }

    case "delete": {
      const { error } = await client
        .from(tablename)
        .delete()
        .eq("id", input.id as string);
      if (error) return JSON.stringify({ error: error.message });
      return JSON.stringify({ success: true });
    }

    default:
      return JSON.stringify({ error: `Unknown command: ${cmd}` });
  }
}
